### ISSUE TITLE
Response seemed to indicate creation failed

### ISSUE THREAD

**Issue by pstorch** [robneild/pocket-query-creator#11]
Seems like something is currently broken with the creation of PQs.

**Comment by robneild** [comment]
Yes, I had a bunch of emails. I am having a look at it
Geocaching changed a bunch of stuff

However, I was just in the middle of updating a bunch of stuff to 6.0

**Comment by robneild** [comment]
Thanks for letting me know. Should be fixed in a few days (probably)

**Comment by pstorch** [comment]
It's fixed with release 4.1.6.
Thanks @robneild.
