### ISSUE TITLE
Download fails because of no access to folders

### ISSUE THREAD

**Issue by gcPhil** [robneild/pocket-query-creator#16]
I got a new device (Blackview BV6000 with Android 6). Everything else is working but I don't get pocket-query-creator running. It don't get access to the download folder and its not possible to set an other one.

With the preset download-path I get an error massage after downloading: "download failed, Error writing the file" (Download fehlgeschlagen, Fehler beim Schreiben der Datei).

When I try to set an individual download path I am not able to access the important folders. When I try to open /sdcard or some the subfolders of /storage I get error message "could not read the folder" (Konnte dieses Verzeichnis nicht lesen). I am able to open some other folders but not that ones leading to the internal or external storage. With other apps its no problem to access this folders.

**Comment by pstorch** [comment]
Have you granted the "Storage" permission to the App?

**Comment by gcPhil** [comment]
Thank you for for your reply. The App got all permissions it asked for but when I watch inside the android app-permission menu it's only listed that it could need to send mails and SMS. I am new to android 6 with this device. Is there an other setting somewhere else I don't know? Non of my apps asked for a special storage permission and all others work.

**Comment by gcPhil** [comment]
Sorry for posting again. I found the right storage setting in the android app list now. I still get no access to subfolders of /storage but access to /sdcard works with this setting and so I am able to download the pq-files.

Thank you for your help. I will close this issue now.
