### ISSUE TITLE
UI function seems broken

### ISSUE THREAD

**Issue by Lineflyer** [robneild/pocket-query-creator#18]
Using up to date version from Google Play:

Either I miss something or the UI is broken.
After starting the app I can do nothing else than enter the setting (via three-dot-button).
I am missing all other buttons/menus/functions:
![screenshot_20170425-230351](https://cloud.githubusercontent.com/assets/949669/25407653/7be9e6ea-2a0b-11e7-9964-4f243e51c89b.png)

Looking at Google Play some users seem to have this problem.

Device:
Samsung S7 on Android 7.0

**Comment by robneild** [comment]
I put in a change that might fix your problem.

**Comment by Lineflyer** [comment]
Confirmed fixed after updating to new version via Google Play!
Thanks!
